'use client'
import { FormEvent, useEffect, useState } from 'react'
import { leadStatuses, type LeadStatus } from '@/lib/virtual-employee'
type Lead = { id: string; name: string; email: string; source: string; plan?: string; message?: string; status: LeadStatus; notes: string; createdAt: string }
export default function VirtualEmployeeReviewQueue() {
  const [token, setToken] = useState(''); const [leads, setLeads] = useState<Lead[]>([]); const [gaps, setGaps] = useState<{ topic: string; count: number }[]>([]); const [statusFilter, setStatusFilter] = useState(''); const [sourceFilter, setSourceFilter] = useState(''); const [error, setError] = useState(''); const [ready, setReady] = useState(false)
  async function load() { const response = await fetch('/api/virtual-employee/admin/leads'); if (!response.ok) { setReady(false); return }; const data = await response.json(); setLeads(data.leads); setGaps(data.gaps); setReady(true) }
  useEffect(() => { void load() }, [])
  async function login(event: FormEvent) { event.preventDefault(); setError(''); const response = await fetch('/api/virtual-employee/admin/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token }) }); if (!response.ok) { setError('Unable to sign in.'); return }; setToken(''); await load() }
  async function update(lead: Lead) { const response = await fetch('/api/virtual-employee/admin/leads', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: lead.id, status: lead.status, notes: lead.notes }) }); if (response.ok) await load() }
  async function logout() { await fetch('/api/virtual-employee/admin/logout', { method: 'POST' }); setReady(false); setLeads([]) }
  if (!ready) return <form onSubmit={login} className="max-w-sm rounded-2xl border bg-white p-6 shadow-card"><h1 className="text-2xl font-bold text-gray-900">Review Queue</h1><p className="mt-2 text-sm text-gray-600">Private access only.</p><input value={token} onChange={(event) => setToken(event.target.value)} type="password" required autoComplete="current-password" placeholder="Admin token" className="mt-4 w-full rounded border p-2"/><button className="btn-primary mt-3 px-4 py-2">Sign in</button>{error && <p className="mt-2 text-sm text-red-600">{error}</p>}</form>
  const visible = leads.filter((lead) => (!statusFilter || lead.status === statusFilter) && (!sourceFilter || lead.source === sourceFilter))
  return <div><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold text-gray-900">Review Queue</h1><p className="mt-1 text-sm text-gray-600">Customer lead data is visible only in this authenticated queue.</p></div><button onClick={logout} className="text-sm font-semibold text-primary-700">Log out</button></div><div className="mt-6 flex flex-wrap gap-3"><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} className="rounded border p-2"><option value="">All statuses</option>{leadStatuses.map((status) => <option key={status}>{status}</option>)}</select><select value={sourceFilter} onChange={(event) => setSourceFilter(event.target.value)} className="rounded border p-2"><option value="">All sources</option>{['pricing', 'virtual-employee', 'seo-audit', 'website-recommendation', 'redesign', 'contact'].map((source) => <option key={source}>{source}</option>)}</select></div><section className="mt-6 rounded-2xl bg-primary-50 p-4"><h2 className="font-bold text-gray-900">Knowledge gaps</h2><p className="mt-1 text-sm text-gray-600">Grouped counts only; unsupported question text is not retained.</p><div className="mt-2 flex gap-4 text-sm">{gaps.map((gap) => <span key={gap.topic}>{gap.topic}: {gap.count}</span>)}</div></section><div className="mt-6 space-y-4">{visible.map((lead) => <article key={lead.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-bold text-gray-900">{lead.name} <span className="text-sm font-normal text-gray-500">{lead.email}</span></h2><span className="text-sm text-gray-500">{lead.source} · {new Date(lead.createdAt).toLocaleString()}</span></div><p className="mt-2 text-sm text-gray-600">Plan: {lead.plan || 'Not selected'}{lead.message ? ` · ${lead.message}` : ''}</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><select value={lead.status} onChange={(event) => setLeads(leads.map((item) => item.id === lead.id ? { ...item, status: event.target.value as LeadStatus } : item))} className="rounded border p-2 text-sm">{leadStatuses.map((status) => <option key={status}>{status}</option>)}</select><input value={lead.notes} onChange={(event) => setLeads(leads.map((item) => item.id === lead.id ? { ...item, notes: event.target.value } : item))} maxLength={2000} placeholder="Internal notes" className="flex-1 rounded border p-2 text-sm"/><button onClick={() => update(lead)} className="btn-secondary px-3 py-2 text-sm">Save</button></div></article>)}{visible.length === 0 && <p className="text-gray-600">No leads match these filters.</p>}</div></div>
}
