import { getPlan, pricingPlans, routineUpdateDefinition, scopeExclusions, SETUP_FEE_PROMOTION_ACTIVE, setupFeeLabel, type PlanId, type PricingPlan } from './pricing'

export type LeadSource = 'pricing' | 'virtual-employee' | 'seo-audit' | 'website-recommendation' | 'redesign' | 'contact'
export type LeadStatus = 'New' | 'Contacted' | 'Proposal Sent' | 'Won' | 'Lost'
export const leadStatuses: readonly LeadStatus[] = ['New', 'Contacted', 'Proposal Sent', 'Won', 'Lost']

export type Guidance = { pages: 'up-to-5' | 'up-to-10' | 'more-than-10'; updates: 'one' | 'unlimited'; seo: boolean; virtualEmployee: boolean }
export type ConciergeAnswer = { text: string; kind: 'answer' | 'unsupported'; topic: string; plans?: PlanId[]; href?: string; linkLabel?: string }

const toolLinks = { recommendation: '/recommendation', seoAudit: '/seo-audit', contact: '/contact', redesign: '/recommendation' }

export function answerQuestion(input: string): ConciergeAnswer {
  const question = input.trim().toLowerCase()
  if (!question || question.length > 500) return unsupported('general')
  if (/\b(legal advice|lawyer|guarantee|guaranteed|uptime|sla|service level agreement)\b/.test(question)) return unsupported('terms')
  if (/\b(cancel|cancellation|end my plan|stop my plan)\b/.test(question)) return { text: 'The published Terms say you may cancel with 30 days written notice. AffordaWeb will provide an export of your website content when the plan is cancelled, and no refunds are issued for partial months. Contact the team for account-specific guidance.', kind: 'answer', topic: 'terms', href: '/terms', linkLabel: 'Read the Terms of Service' }
  if (/\b(refund|money back|partial month)\b/.test(question)) return { text: 'The published Terms state that no refunds are issued for partial months. Contact the team before making a billing decision or for help with a specific account.', kind: 'answer', topic: 'terms', href: '/terms', linkLabel: 'Read the refund terms' }
  if (/\b(ownership|who owns|intellectual property|website content)\b/.test(question)) return { text: 'You retain ownership of content you provide. The published Terms say AffordaWeb owns the design work until full payment is received, after which ownership transfers to the client.', kind: 'answer', topic: 'terms', href: '/terms', linkLabel: 'Read the ownership terms' }
  if (/\b(billing cycle|billed|monthly subscription|due date|nonpayment|non-payment)\b/.test(question)) return { text: 'Services are provided as monthly subscriptions. The published Terms say monthly fees are billed in advance and due at the start of each billing cycle; nonpayment may result in service suspension.', kind: 'answer', topic: 'terms', href: '/terms', linkLabel: 'Read the payment terms' }
  if (/\b(terms|contract|agreement|acceptable use|liability)\b/.test(question)) return { text: 'AffordaWeb publishes its service, payment, cancellation, ownership, acceptable-use, and liability terms online. Review the Terms of Service and contact the team if you need an interpretation for your situation.', kind: 'answer', topic: 'terms', href: '/terms', linkLabel: 'Read the Terms of Service' }
  if (/\b(privacy|personal data|data policy|cookies)\b/.test(question)) return { text: 'AffordaWeb publishes its privacy practices on the Privacy Policy page. For a question about your own data, contact the team directly.', kind: 'answer', topic: 'privacy', href: '/privacy', linkLabel: 'Read the Privacy Policy' }
  if (/^(hi|hello|hey|good (morning|afternoon|evening))\b/.test(question)) return { text: 'Hello! I can help with AffordaWeb services, plans, pricing, timelines, hosting, SEO, redesigns, and service areas. What would you like to know?', kind: 'answer', topic: 'welcome' }
  if (/\b(who are you|who is affordaweb|about (you|affordaweb)|company|founded|team)\b/.test(question)) return { text: 'AffordaWeb Solutions is a Filipino team of designers, developers, and SEO specialists founded in 2021. The company builds and manages affordable websites for small businesses in the United States and internationally.', kind: 'answer', topic: 'company', href: '/about', linkLabel: 'About AffordaWeb' }
  if (/\b(virtual employee|chatbot|knowledge base|review queue|knowledge gap)\b/.test(question)) {
    const plan = getPlan('virtual-employee')
    return { text: `${plan.description} It answers from business information you approve, identifies knowledge gaps, and provides a review queue with human oversight. It does not make binding commitments or answer outside the approved knowledge base. The plan is $${plan.monthlyPrice}/mo and includes everything in Business.`, kind: 'answer', topic: 'virtual-employee', plans: ['virtual-employee'], href: '/virtual-employee', linkLabel: 'Explore the Virtual Employee' }
  }
  if (/\bstarter\b/.test(question) && /\b(plan|price|cost|include|included|feature|offer|come with)\b/.test(question)) return planAnswer(getPlan('starter'))
  if (/\bbusiness plan\b/.test(question) || (/\bbusiness\b/.test(question) && /\b(price|cost|include|included|feature|come with)\b/.test(question))) return planAnswer(getPlan('business'))
  if (/\b(which plan|best plan|right plan|recommend a plan|plan should i|choose a plan)\b/.test(question)) return { text: 'Starter fits a professional site of up to 5 pages with one routine update per month. Business fits up to 10 pages and adds SEO optimization, Google Analytics, a contact form, and unlimited routine updates. Virtual Employee adds approved-knowledge visitor support and a review workflow. I can provide more precise guidance on the Virtual Employee page.', kind: 'answer', topic: 'plan-guidance', plans: ['starter', 'business', 'virtual-employee'], href: '/virtual-employee#ve-guidance', linkLabel: 'Use plan guidance' }
  if (/\b(setup fee|setup cost|upfront fee|one-time fee)\b/.test(question)) return { text: `Starter: $${getPlan('starter').monthlyPrice}/mo; Business: $${getPlan('business').monthlyPrice}/mo; Virtual Employee: $${getPlan('virtual-employee').monthlyPrice}/mo. Setup fees are currently waived. The normal one-time fees are Starter $${getPlan('starter').setupFee}, Business $${getPlan('business').setupFee}, and Virtual Employee $${getPlan('virtual-employee').setupFee}.`, kind: 'answer', topic: 'pricing', plans: ['starter', 'business', 'virtual-employee'], href: '/pricing', linkLabel: 'View current pricing' }
  if (/\b(price|pricing|cost|monthly|how much|setup fee)\b/.test(question)) {
    const prices = pricingPlans.map((plan) => `${plan.name}: $${plan.monthlyPrice}/mo`).join('; ')
    return { text: `${prices}. ${SETUP_FEE_PROMOTION_ACTIVE ? 'Setup fees are currently waived.' : 'Each plan has a one-time setup fee.'} See the plan comparison for inclusions.`, kind: 'answer', topic: 'pricing', plans: pricingPlans.map((plan) => plan.id), href: '/pricing', linkLabel: 'Compare plans' }
  }
  if (/\b(how many pages|page limit|number of pages|website pages)\b/.test(question)) return { text: 'Starter includes up to 5 website pages. Business and Virtual Employee include up to 10. Projects needing more than 10 pages require a custom quote.', kind: 'answer', topic: 'pages', plans: ['starter', 'business', 'virtual-employee'], href: '/contact', linkLabel: 'Request a custom quote' }
  if (/\b(how long|timeline|launch|turnaround|business days|when.*ready)\b/.test(question)) return { text: 'Most websites launch in 10 to 15 business days after AffordaWeb receives your content, preferences, and feedback. E-commerce and more complex projects may take longer.', kind: 'answer', topic: 'timeline', href: '/services', linkLabel: 'See how it works' }
  if (/\b(routine update|content update|content change|unlimited update|maintenance)\b/.test(question)) return { text: `${routineUpdateDefinition} Starter includes one routine update per month; Business and Virtual Employee include unlimited routine updates.`, kind: 'answer', topic: 'maintenance', plans: ['starter', 'business', 'virtual-employee'], href: '/pricing', linkLabel: 'Compare update allowances' }
  if (/\b(update plugin|plugin update|security|backups?|monitoring|technical check|keep.*running)\b/.test(question)) return { text: 'Every plan includes ongoing website support, regular software and security updates, backups, and performance monitoring. Routine content-update allowances depend on the selected plan.', kind: 'answer', topic: 'maintenance', href: '/services/maintenance', linkLabel: 'Explore website maintenance' }
  if (/\b(e-?commerce|online store|sell online|products|shopping cart|checkout)\b/.test(question)) return { text: 'AffordaWeb designs mobile-friendly online stores with secure payment processing and publicly describes stores with up to 30 products. E-commerce scope and timing depend on the required features, so the team provides a custom quote.', kind: 'answer', topic: 'ecommerce', href: '/contact', linkLabel: 'Request an e-commerce quote' }
  if (/\b(custom design|responsive|mobile friendly|mobile-friendly|branding|colors|colour|layout|template)\b/.test(question)) return { text: 'AffordaWeb creates custom, mobile-responsive websites around your branding, colors, goals, and voice. The published design service emphasizes clean code, fast loading, smooth navigation, and conversion-focused layouts rather than a generic free template.', kind: 'answer', topic: 'design', href: '/services/design', linkLabel: 'Explore website design' }
  if (/\b(speed|fast loading|performance|page speed|pagespeed)\b/.test(question)) return { text: 'AffordaWeb builds sites with clean code and fast-loading, mobile-friendly layouts, then monitors website performance as part of managed support. Results depend on the site and its content, so no performance guarantee is implied.', kind: 'answer', topic: 'performance', href: '/services/design', linkLabel: 'View design features' }
  if (/\b(contact form|inquiry form|enquiry form|lead form)\b/.test(question)) return { text: 'Contact-form integration is included in the Business and Virtual Employee plans. Starter does not list a contact form in its published inclusions.', kind: 'answer', topic: 'contact-form', plans: ['business', 'virtual-employee'], href: '/pricing', linkLabel: 'Compare plan features' }
  if (/\b(google analytics|traffic analytics|visitor analytics|analytics integration)\b/.test(question)) return { text: 'Google Analytics integration is included in the Business and Virtual Employee plans. It is not listed as a Starter inclusion.', kind: 'answer', topic: 'analytics', plans: ['business', 'virtual-employee'], href: '/pricing', linkLabel: 'Compare plan features' }
  if (/\b(copywriting|write my content|new page|custom development|third-party|third party|integration|new functionality)\b/.test(question)) return { text: `${scopeExclusions[0]} Routine updates also exclude new page design, copywriting, e-commerce work, integrations, and strategy projects.`, kind: 'answer', topic: 'custom-scope', href: '/contact', linkLabel: 'Discuss a custom project' }
  if (/\b(redesign|existing (site|website)|migrate|migration|old website)\b/.test(question)) return { text: 'AffordaWeb can redesign an existing website with a modern mobile-friendly layout, improved performance, and a conversion-focused structure while preserving existing content and SEO where practical.', kind: 'answer', topic: 'redesign', href: '/services/redesign', linkLabel: 'Explore website redesign' }
  if (/\b(seo audit|audit my site|check my seo|seo score)\b/.test(question)) return { text: 'The free SEO Audit analyzes a website for technical and on-page issues and provides an initial score and findings. No account or credit card is required for the free preview.', kind: 'answer', topic: 'tools', href: '/seo-audit', linkLabel: 'Run a free SEO audit' }
  if (/\b(seo|search engine|google ranking|rank|analytics)\b/.test(question)) return { text: 'Every plan includes basic SEO setup. Business and Virtual Employee add SEO optimization and Google Analytics integration. Rankings cannot be guaranteed, but you can use the free SEO Audit for site-specific findings.', kind: 'answer', topic: 'seo', plans: ['starter', 'business', 'virtual-employee'], href: '/seo-audit', linkLabel: 'Run a free SEO audit' }
  if (/\b(hosting|ssl|certificate|professional email|email account|backup|security update)\b/.test(question)) return { text: 'Every plan includes managed hosting, an SSL certificate, monitoring, maintenance, and one 1 GB professional email account. You do not need to purchase separate hosting.', kind: 'answer', topic: 'hosting', plans: ['starter', 'business', 'virtual-employee'], href: '/services/hosting', linkLabel: 'View hosting details' }
  if (/\b(new jersey|nj|newark|jersey city|paterson|cherry hill|edison|trenton)\b/.test(question)) return { text: 'AffordaWeb serves businesses throughout New Jersey, including all counties and published local coverage for Newark, Jersey City, Paterson, Cherry Hill, Edison, Trenton, and other communities.', kind: 'answer', topic: 'service-area', href: '/new-jersey', linkLabel: 'View New Jersey services' }
  if (/\b(fresno|clovis|central valley|madera|tulare|kings county)\b/.test(question)) return { text: "AffordaWeb serves Fresno, Clovis, Madera, Kings and Tulare counties, and other businesses across California's Central Valley through a remote website process.", kind: 'answer', topic: 'service-area', href: '/fresno', linkLabel: 'View Fresno services' }
  if (/\b(houston|harris county|fort bend|montgomery county|galveston|brazoria)\b/.test(question)) return { text: 'AffordaWeb serves Greater Houston, including Harris, Fort Bend, Montgomery, Galveston, and Brazoria counties.', kind: 'answer', topic: 'service-area', href: '/houston', linkLabel: 'View Houston services' }
  if (/\b(los angeles|la county|san fernando|south bay|orange county|inland empire|ventura)\b/.test(question)) return { text: 'AffordaWeb serves the Los Angeles region, including LA County, the San Fernando Valley, South Bay, San Gabriel Valley, Orange County, Inland Empire, and Ventura County.', kind: 'answer', topic: 'service-area', href: '/los-angeles', linkLabel: 'View Los Angeles services' }
  if (/\b(philadelphia|philly|montgomery county|bucks county|delaware county|chester county|south jersey)\b/.test(question)) return { text: 'AffordaWeb serves Philadelphia and the surrounding Montgomery, Bucks, Delaware, and Chester counties, as well as South Jersey.', kind: 'answer', topic: 'service-area', href: '/philadelphia', linkLabel: 'View Philadelphia services' }
  if (/\b(manila|philippines|metro manila|central luzon|calabarzon|visayas|mindanao)\b/.test(question)) return { text: 'AffordaWeb serves clients in Metro Manila, Central Luzon, CALABARZON, the Visayas, and Mindanao, and also works with clients internationally through a remote process.', kind: 'answer', topic: 'service-area', href: '/affordable-web-design-services-in-manila', linkLabel: 'View Philippines services' }
  if (/\b(location|service area|serve|based|new jersey|fresno|houston|los angeles|philadelphia|manila|philippines|nationwide|united states|usa)\b/.test(question)) return { text: "AffordaWeb works remotely with small businesses across the United States and internationally. Published service areas include New Jersey, Fresno and California's Central Valley, Greater Houston, Los Angeles, Philadelphia, and the Philippines.", kind: 'answer', topic: 'service-area', href: '/contact', linkLabel: 'Ask about your location' }
  if (/\b(process|how does it work|how do (we|i) start|getting started|start a website)\b/.test(question)) return { text: 'The process has three stages: share your goals and preferences, review a custom mobile-first and SEO-ready website, then launch with managed hosting and ongoing support. The team handles design, development, hosting setup, and launch.', kind: 'answer', topic: 'process', href: '/recommendation', linkLabel: 'Get a website recommendation' }
  if (/\b(contact|email|talk to|speak to|human|person|quote|consultation|support hours|open hours)\b/.test(question)) return { text: 'You can request a free, no-obligation quote or email hello@affordawebsolutions.com. Support hours are Monday through Friday, 9:00 AM to 5:00 PM, and the team aims to respond within 24 hours.', kind: 'answer', topic: 'contact', href: '/contact', linkLabel: 'Contact the team' }
  if (/\b(payment|pay|credit card|visa|mastercard|american express|paypal)\b/.test(question)) return { text: 'AffordaWeb publishes Visa, Mastercard, American Express, and PayPal as accepted payment methods. Contact the team for billing questions specific to your account.', kind: 'answer', topic: 'payment', href: '/contact', linkLabel: 'Ask a billing question' }
  if (/\b(technical knowledge|coding|code|provide content|need content|what do you need from me)\b/.test(question)) return { text: 'You do not need technical or coding knowledge. To begin, share your goals, design preferences, business information, and available text and images. AffordaWeb handles design, development, hosting setup, and launch.', kind: 'answer', topic: 'requirements', href: '/contact', linkLabel: 'Start a project' }
  if (/\b(free tool|website recommendation|recommendation tool|redesign plan)\b/.test(question)) return { text: 'The free Website Recommendation tool creates a personalized website or redesign direction from your business type, goals, and existing website. It does not require an account or credit card.', kind: 'answer', topic: 'tools', href: '/recommendation', linkLabel: 'Try Website Recommendation' }
  if (/\b(portfolio|examples|work|websites built)\b/.test(question)) return { text: 'You can review examples of AffordaWeb website work in the portfolio.', kind: 'answer', topic: 'portfolio', href: '/portfolio', linkLabel: 'View the portfolio' }
  if (/\b(blog|guides?|articles?|resources?|learn about websites)\b/.test(question)) return { text: 'The AffordaWeb blog publishes website design, maintenance, SEO, hosting, and small-business website guides.', kind: 'answer', topic: 'resources', href: '/blog', linkLabel: 'Browse website guides' }
  if (/\b(freelancer|startup|local business|small business|service provider|who do you work with|industries)\b/.test(question)) return { text: 'AffordaWeb primarily works with small businesses, freelancers, local service providers, and startups that need a professional website or have outgrown a basic template.', kind: 'answer', topic: 'clients', href: '/portfolio', linkLabel: 'See client work' }
  if (/\b(new website|website design|services|affordaweb|what do you do|what do you offer)\b/.test(question)) return { text: 'AffordaWeb offers custom website design, redesign, managed hosting, maintenance, SEO support, e-commerce projects, and governed Virtual Employee experiences for small businesses.', kind: 'answer', topic: 'services', plans: ['starter', 'business', 'virtual-employee'], href: '/services', linkLabel: 'Explore services' }
  return unsupported('general')
}

function planAnswer(plan: PricingPlan): ConciergeAnswer {
  return { text: `${plan.name} is $${plan.monthlyPrice}/mo with ${setupFeeLabel(plan).toLowerCase()}. It includes ${plan.inclusions.join(', ')}.`, kind: 'answer', topic: 'pricing', plans: [plan.id], href: '/pricing', linkLabel: 'Compare all plans' }
}

function unsupported(topic: string): ConciergeAnswer {
  return { text: 'I do not have approved information to answer that accurately. A team member can help with this question.', kind: 'unsupported', topic, href: '/contact', linkLabel: 'Ask the team' }
}

export function recommendPlan(guidance: Guidance): { plan: PlanId | null; text: string } {
  if (guidance.pages === 'more-than-10') return { plan: null, text: 'The published plans list up to 10 website pages. Please request a quote so the team can discuss your needs.' }
  const plan = guidance.virtualEmployee ? 'virtual-employee' : guidance.pages === 'up-to-10' || guidance.updates === 'unlimited' || guidance.seo ? 'business' : 'starter'
  const selected = getPlan(plan)
  return { plan, text: `Based on the options selected, ${selected.name} is the closest published plan: $${selected.monthlyPrice}/mo, ${setupFeeLabel(selected)}. This is guidance from the catalog, not a custom quote.` }
}

export function isLeadSource(value: unknown): value is LeadSource {
  return typeof value === 'string' && ['pricing', 'virtual-employee', 'seo-audit', 'website-recommendation', 'redesign', 'contact'].includes(value)
}

export { toolLinks }
